dist: xenial
language: "python"

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "pypy3.5-6.0"

install:
    - "pip install ."
    - "pip install -U coveralls flake8"

script:
    - "coverage run --include='cdblib/*.py' setup.py test"
    - "coverage run --include='cdblib/*.py' setup.py test"
    - "ENABLE_DJB_HASH_CEXT=1 coverage run --include='cdblib/*.py' setup.py test"
    - "flake8 ."

notifications:
    - email: false

after_success:
    - "coveralls"
